// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8zlFc2a0-9_z4KkKmgsjg5rmtM7LO9pQ',
    appId: '1:1059189595415:web:b9306655bb708d919beb52',
    messagingSenderId: '1059189595415',
    projectId: 'internship-app-2d641',
    authDomain: 'internship-app-2d641.firebaseapp.com',
    storageBucket: 'internship-app-2d641.appspot.com',
    measurementId: 'G-1GD5F3NWTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYdnMeeDlQtKIOt1X1d7VpPggZ8VocJkE',
    appId: '1:1059189595415:android:ef7e466593d8f2949beb52',
    messagingSenderId: '1059189595415',
    projectId: 'internship-app-2d641',
    storageBucket: 'internship-app-2d641.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC--YSoudWmUGNOX1nGr1nJPQdDI55003c',
    appId: '1:1059189595415:ios:8da03e656712fbef9beb52',
    messagingSenderId: '1059189595415',
    projectId: 'internship-app-2d641',
    storageBucket: 'internship-app-2d641.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC--YSoudWmUGNOX1nGr1nJPQdDI55003c',
    appId: '1:1059189595415:ios:8da03e656712fbef9beb52',
    messagingSenderId: '1059189595415',
    projectId: 'internship-app-2d641',
    storageBucket: 'internship-app-2d641.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8zlFc2a0-9_z4KkKmgsjg5rmtM7LO9pQ',
    appId: '1:1059189595415:web:6f2f97cde370ff949beb52',
    messagingSenderId: '1059189595415',
    projectId: 'internship-app-2d641',
    authDomain: 'internship-app-2d641.firebaseapp.com',
    storageBucket: 'internship-app-2d641.appspot.com',
    measurementId: 'G-WQRRS9BHFW',
  );
}
